### ISSUE TITLE
bf.sed fails for this Hello World!

### ISSUE THREAD

**Issue by rdebath** [svbatalov/bf.sed#1]
This "Hello World!" prints a "H" then burns.

``` bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

And this one _should_ print "brainfuck"
``` bf
++++++[>++++<-]>[>[+++++>][>]-[<][[]]>-]
>>>>-.<<<.>>>-.<+.<+.>---.<<+++.>>---.<---.
```

**Comment by svbatalov** [comment]
Hi!

Yeah, there are bugs. Maybe, when I have time, I'll look into it. It was so long ago. Meanwhile, you may try to debug it yourself and even if fail, you'll learn sed. After all, sed is also a kind of brainfuck :)

**Comment by svbatalov** [comment]
Oh, I see you use complex version of hello world from wikipedia, which `uses cell values below zero and so doesn't work on fascist, score-computing interpreters.` Negative numbers are not supported. Regular version works just fine:
```
$ ./bf.sed <<<  '++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.'
H
e
l
l
o

W
o
r
l
d
!

%|;0,0,72,100,87,33,:10,
```
(Ignore junk at the end -- it is the state of the interpreter)

**Comment by rdebath** [comment]
OOps, sorry I usually notice that limitation, I suppose, if you have to construct arithmetic, I assumed you'd construct the normal BF style (like [I did](https://github.com/rdebath/Brainfuck/blob/master/extras/bf.sed))  Though it probably didn't help that you can only run one line of BF code.

BTW: I didn't put the more complex one on Wikipedia, only the Eso-wiki, and I now prefer a 99 character HW over the three 106 character ones; it's easier to understand....

``` bf
++++[>++++<-]>[>+>++>[+++++++>]+++[<]>-]>>>>>>>>-.<<<<.<..+++.<.>>>>.<<<.+++.------.>-.<<+.<------.
```

Maybe I should write it up.
